<header class="header">
    <div class="menu-box">
        <div class="logo-box">
            <a href="index.php"><img class="logo" src="img/logoweb.png" alt="Logo"></a>
        </div>
        <nav class="nav-box">
            <a href="index.php">Présentation</a>
            <a href="psychomotricite.php">Psychomotricite</a>
            <a href="posturologie.php">Posturologie</a>
            <a href="reflexe-archaique.php">Reflexe-archaique</a>
            <a href="index.php#contact">Contact</a>
        </nav>
    </div>
</header>