<main>
    <section id="welcome" class="welcome-wrap">
        <video muted autoplay loop>
            <source type="video/mp4" src="video/video.mp4" media="(orientation: landscape)">
            <source type="video/webm" src="https://www.youtube.com/embed/BJfhXjUz8P0" media="(orientation: landscape)">
            <source type="video/mp4" src="video/video.mp4" media="(orientation: portrait)">
            <source type="video/webm" src="https://www.youtube.com/embed/BJfhXjUz8P0" media="(orientation: portrait)">
        </video>
    </section>
    <section id="whoIam">
    </section>
    <section id="contact">
    </section>
    <section id="map">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d872.077992180653!2d4.809495129255446!3d44.59787845363016!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x12b56a002514476b%3A0xaabac80a3e4c0544!2sCabinet+de+kin%C3%A9sith%C3%A9rapie+et+d&#39;ost%C3%A9opathie!5e1!3m2!1sfr!2sfr!4v1522855762982" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
    </section>
</main>
