<main>
    <section id="welcome">
        <video muted autoplay loop>
            <source type="video/mp4" src="video/video.mp4" media="(orientation: landscape)">
            <source type="video/webm" src="https://www.youtube.com/embed/BJfhXjUz8P0" media="(orientation: landscape)">
            <source type="video/mp4" src="video/video.mp4" media="(orientation: portrait)">
            <source type="video/webm" src="https://www.youtube.com/embed/BJfhXjUz8P0" media="(orientation: portrait)">
        </video>
    </section>
    <section id="contact">
    </section>
    <section id="googlemap">

    </section>
</main>
