<!Doctype HTML>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <title>Psychomotricien David Ravel</title>
    <link rel="stylesheet" type="text/css" href="slick/slick.css"/>
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower|Oleo+Script|Roboto" rel="stylesheet">
    <link rel="stylesheet" href="css/style.css">
    <script
        src="https://code.jquery.com/jquery-3.2.1.js"
        integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE="
        crossorigin="anonymous">
    </script>
    <script src="https://use.fontawesome.com/3a17084bdb.js"></script>
</head>
<body>
    <?php include "header.phtml"; ?>
    <?php include $page; ?>
    <script type="text/javascript" src="js/main.js"></script>
</body>
<footer>
</footer>
</html>